### ISSUE TITLE
Tracking Issue 10.3.0-beta.2

### ISSUE THREAD

**Issue by quinn-semele** [quinn-semele/expanded-storage#11]
# Issues
- [x] When implementing better carry-on support I broke chest unmerging with the storage mutator.
- [x] Verify swap theme and conversion kits work on Forge.
- [x] Improve detection for whether a player should be able to open a chest since there is a few edge cases where it will say it's locked.
- [x] Fix Fabric and Quilt's dependencies not being set properly on CurseForge & Modrinth.
- [x] Re-run data generators for Forge & Thread.
- [x] Conversion recipes for entities seem to be broken on Forge.
# What is this?
This is simply an issue to keep track of all the things needed to be done before releasing `10.3.0-beta.2` for `1.20.1`.
I may have missed some issues for the original release.
