### ISSUE TITLE
Tracking Issue: 10.3.0

### ISSUE THREAD

**Issue by quinn-semele** [quinn-semele/expanded-storage#9]
# Issues
- [x] https://github.com/quinn-semele/expanded-storage/issues/6
- [x] https://github.com/quinn-semele/expanded-storage/issues/8
- [x] https://github.com/quinn-semele/expanded-storage/issues/5
- [x] https://github.com/quinn-semele/expanded-storage/issues/10
- [x] Update all dependencies and fix mod compat
- [x] Check for differences between fabric only codebase (closed source) and this new codebase.
- [x] Check for binary changes between the old release, this release and the fabric only release and try to minimise them.
- [x] Verify the mod runs in production
- [x] Fix mini chests forgetting about sparrows when being carried with our Carrier compat.
# What is this?
This is simply an issue to keep track of all the things needed to be done before releasing `10.3.0` for `1.20.1`.
This is subject to change as some things may have been forgotten.
